<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DivisaSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {

        DB::table('divisas')->insert([
            ['codigo' => 'AED', 'nombre' => 'Dirham-Emiratos Árabes Unidos'],
            ['codigo' => 'ANG', 'nombre' => 'Florín antillano neerlandés'],
            ['codigo' => 'ARS', 'nombre' => 'Peso argentino'],
            ['codigo' => 'AUD', 'nombre' => 'Dólar australiano'],
            ['codigo' => 'BBD', 'nombre' => 'Dólar de Barbados'],
            ['codigo' => 'BDT', 'nombre' => 'Taka de Bangladesh'],
            ['codigo' => 'BHD', 'nombre' => 'Dinar Bahreiní'],
            ['codigo' => 'BGN', 'nombre' => 'Lev búlgaro'],
            ['codigo' => 'BOB', 'nombre' => 'Boliviano de Bolivia'],
            ['codigo' => 'BRL', 'nombre' => 'Real Brasileño'],
            ['codigo' => 'CAD', 'nombre' => 'Dólar canadiense'],
            ['codigo' => 'CHF', 'nombre' => 'Franco suizo'],
            ['codigo' => 'CLP', 'nombre' => 'Peso chileno'],
            ['codigo' => 'CNY', 'nombre' => 'Yuan Chino'],
            ['codigo' => 'COP', 'nombre' => 'Peso colombiano'],
            ['codigo' => 'CRC', 'nombre' => 'Colón costarricense'],
            ['codigo' => 'CZK', 'nombre' => 'Corona Checa'],
            ['codigo' => 'DKK', 'nombre' => 'Corona Danesa'],
            ['codigo' => 'DOP', 'nombre' => 'Peso dominicano'],
            ['codigo' => 'DZD', 'nombre' => 'Dinar algerino'],
            ['codigo' => 'EEK', 'nombre' => 'Corona estonia'],
            ['codigo' => 'EGP', 'nombre' => 'Libra Egipcia'],
            ['codigo' => 'EUR', 'nombre' => 'Euro'],
            ['codigo' => 'FJD', 'nombre' => 'Dólar fijiano'],
            ['codigo' => 'GBP', 'nombre' => 'Libra Esterlina'],
            ['codigo' => 'HKD', 'nombre' => 'Dólar de Hong Kong'],
            ['codigo' => 'HNL', 'nombre' => 'Lempira hondureño'],
            ['codigo' => 'HRK', 'nombre' => 'Kuna croata'],
            ['codigo' => 'HUF', 'nombre' => 'Florín húngaro'],
            ['codigo' => 'IDR', 'nombre' => 'Rupia Indonesia'],
            ['codigo' => 'ILS', 'nombre' => 'Shekel Israelí'],
            ['codigo' => 'INR', 'nombre' => 'Rupia Hindú'],
            ['codigo' => 'ISK', 'nombre' => 'Corona Islandesa'],
            ['codigo' => 'JMD', 'nombre' => 'Dólar Jamaiquino'],
            ['codigo' => 'JOD', 'nombre' => 'Dinar Jordano'],
            ['codigo' => 'JPY', 'nombre' => 'Yen Japonés'],
            ['codigo' => 'KES', 'nombre' => 'Chelín Keniano'],
            ['codigo' => 'KRW', 'nombre' => 'Won surcoreano'],
            ['codigo' => 'KWD', 'nombre' => 'Dinar kuwaití'],
            ['codigo' => 'LBP', 'nombre' => 'Libra Libanesa'],
            ['codigo' => 'LKR', 'nombre' => 'Rupia Esrilanquesa'],
            ['codigo' => 'LTL', 'nombre' => 'Litas lituana'],
            ['codigo' => 'LVL', 'nombre' => 'Lats Letón'],
            ['codigo' => 'MAD', 'nombre' => 'Dirham de Marreucos'],
            ['codigo' => 'MDL', 'nombre' => 'Leu moldavo'],
            ['codigo' => 'MKD', 'nombre' => 'Denar macedonio'],
            ['codigo' => 'MTL', 'nombre' => 'Lira maltesa'],
            ['codigo' => 'MUR', 'nombre' => 'Rupia mauricia'],
            ['codigo' => 'MVR', 'nombre' => 'Rufiyaa maldiva'],
            ['codigo' => 'MXN', 'nombre' => 'Peso mexicano'],
            ['codigo' => 'MYR', 'nombre' => 'Ringgit Malayo'],
            ['codigo' => 'NAD', 'nombre' => 'Dólar Namibio'],
            ['codigo' => 'NGN', 'nombre' => 'Naira Nigeria'],
            ['codigo' => 'NIO', 'nombre' => 'Córdoba nicaragüense'],
            ['codigo' => 'NOK', 'nombre' => 'Corona noruega'],
            ['codigo' => 'NPR', 'nombre' => 'Rupia nepalí'],
            ['codigo' => 'NZD', 'nombre' => 'Dólar neozelandés'],
            ['codigo' => 'OMR', 'nombre' => 'Rial Omaní'],
            ['codigo' => 'PAB', 'nombre' => 'Balboa Panameño'],
            ['codigo' => 'PEN', 'nombre' => 'Nuevo sol Perú'],
            ['codigo' => 'PGK', 'nombre' => 'Kina de Papúa Nueva Guinea'],
            ['codigo' => 'PHP', 'nombre' => 'Peso filipino'],
            ['codigo' => 'PKR', 'nombre' => 'Rupia paquistaní'],
            ['codigo' => 'PLN', 'nombre' => 'Zloty Polaco'],
            ['codigo' => 'PYG', 'nombre' => 'Guaraní paraguayo'],
            ['codigo' => 'QAR', 'nombre' => 'Riyal Qatarí'],
            ['codigo' => 'RON', 'nombre' => 'Leu Rumano'],
            ['codigo' => 'RUB', 'nombre' => 'Rublo ruso'],
            ['codigo' => 'SAR', 'nombre' => 'Riyal Saudí'],
            ['codigo' => 'SCR', 'nombre' => 'Rupia de Seychelles'],
            ['codigo' => 'SEK', 'nombre' => 'Corona sueca'],
            ['codigo' => 'SGD', 'nombre' => 'Dólar de Singapur'],
            ['codigo' => 'SKK', 'nombre' => 'Corona eslovaca'],
            ['codigo' => 'SLL', 'nombre' => 'Leone de Sierra Leona'],
            ['codigo' => 'THB', 'nombre' => 'Baht Thailandés'],
            ['codigo' => 'TND', 'nombre' => 'Dinar tunecino'],
            ['codigo' => 'TRY', 'nombre' => 'Lira turca'],
            ['codigo' => 'TTD', 'nombre' => 'Dólar de Trinidad y Tobago'],
            ['codigo' => 'TWD', 'nombre' => 'Dólar taiwanés'],
            ['codigo' => 'TZS', 'nombre' => 'Chelín tanzano'],
            ['codigo' => 'UAH', 'nombre' => 'UGrivna Ucrania'],
            ['codigo' => 'UGX', 'nombre' => 'Chelín ugandés'],
            ['codigo' => 'USD', 'nombre' => 'Dólar americano'],
            ['codigo' => 'UYU', 'nombre' => 'Peso uruguayo'],
            ['codigo' => 'UZS', 'nombre' => 'Som uzbeko'],
            ['codigo' => 'VEF', 'nombre' => 'Bolívar  venezolano'],
            ['codigo' => 'VND', 'nombre' => 'Dong vietnamita'],
            ['codigo' => 'XAF', 'nombre' => 'Franco CFA de África Central'],
            ['codigo' => 'XCD', 'nombre' => 'Dólar del Caribe Oriental'],
            ['codigo' => 'XOF', 'nombre' => 'Franco CFA de África Occidental'],
            ['codigo' => 'YER', 'nombre' => 'Rial yemení (de Yemen)'],
            ['codigo' => 'ZAR', 'nombre' => 'Rand sudafricano'],
            ['codigo' => 'ZMK', 'nombre' => 'Kwacha zambiano'],
        ]);
    }

}
